nelmio_api_doc:
    documentation:
        info:
            title: "TOTS Event Booking API"
            description: "Documentación generada automáticamente"
            version: "1.0.0"
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
        security:
            - BearerAuth: []
    areas:
        default:
            path_patterns: ["^/api"]
