nelmio_api_doc:
    documentation:
        info:
            title: "TOTS Event Booking API"
            description: "Documentación generada automáticamente"
            version: "1.0.0"
    areas:
        default:
            path_patterns: ["^/api"]
